In [224]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [225]:
def load_text_file_to_array(text_fp):
    nums = []
    file = open(text_fp, "r")
    for line in file:
        nums.append(int(line.strip()))
    nums = np.array(nums)
    return nums

In [226]:
fp = 'coursera_algo_nums_QuickSort.txt'
nums = load_text_file_to_array(fp)
nums[:10]

array([2148, 9058, 7742, 3153, 6324,  609, 7628, 5469, 7017,  504])

In [227]:
fewer_nums = nums[:100]
fewer_nums

array([2148, 9058, 7742, 3153, 6324,  609, 7628, 5469, 7017,  504, 4092,
       1582, 9572, 1542, 5697, 2081, 4218, 3130, 7923, 9595, 6558, 3859,
       9832, 3062, 6788, 7578, 7432,  479, 8439, 9079, 7173, 2667, 2770,
       2655,  972, 4264, 2014, 3171, 4715,  345, 4388, 3816, 8887, 3915,
       3490, 2327,  123, 4596, 4307, 8737, 4007, 6798, 6551, 1627, 1190,
       4984, 2480, 3404, 2027, 4778, 2951, 2795, 5002, 8121, 8910, 9593,
       5254,  448, 6237, 5565, 1816,  392, 8143, 9310, 9293, 3138, 4869,
       6756,  872, 6183, 3517, 3513, 1676, 5498, 9172, 5739, 6108, 7538,
       7671, 5780, 8666,  540, 9771, 6837, 9341, 1590, 5689, 1605, 1103,
       5859])

In [296]:
def choose_pivot(arr, l_endpt_idx, r_endpt_idx, method='first'):
    if method == 'first':
        return l_endpt_idx
    elif method == 'last':
        return r_endpt_idx
    elif method == 'median':
#         if len(arr) % 2 == 0:
        arr_len = r_endpt_idx - l_endpt_idx
        if arr_len % 2 == 0:
            mid_idx = arr_len // 2 - 1
        else:
            mid_idx = arr_len // 2
        nums = [arr[l_endpt_idx], arr[mid_idx], arr[r_endpt_idx]]
        print(f"nums in choose_pivot(): {nums}")
        median = np.median(nums)
        print(f"median in choose_pivot(): {median}, will return {np.where(arr == median)[0][0]}")
#         return int(median)
        return np.where(arr == median)[0][0]
    else:
        raise ValueError("method must be first, last, or median")

In [297]:
def partition(arr, l_idx, r_idx):
    print(f"array to partition: {arr[l_idx:r_idx]}")
    p = arr[l_idx] # pivot is the first element in the subarry to be partitioned
    print(f"pivot={p}")
    i = l_idx + 1 # i is the boundary between elements greater than and less than pivot
    for j in range(l_idx+1, r_idx): # j is boundary between looked at and not
        print(f"j={j}, i={i}")#, array={arr[l_idx:r_idx]}
        if arr[j] < p:
            print(f"{arr[j]} is less than pivot ({p}) - do work")
            num = arr[i]
            arr[i] = arr[j]
            arr[j] = num
#             print(f"new array: {arr[l_idx:r_idx]}")
            i += 1
    new_pivot_idx = i - 1
    swap_num = arr[new_pivot_idx]
    arr[new_pivot_idx] = p
    arr[l_idx] = swap_num
    print(f"final array in partition: {arr}, returning new pivot index {new_pivot_idx}")
    return new_pivot_idx

In [298]:
def move_pivot_to_first(arr, l_endpt, pivot_idx):
    pivot = arr[pivot_idx]
    first = arr[l_endpt]
    arr[l_endpt] = pivot
    arr[pivot_idx] = first
    return

In [299]:
def quick_sort(arr, l_endpt, r_endpt, pivot_method):
    print(f"original array: {arr}")
    print(f"pivot_method: {pivot_method}") 
    print(f"left: {l_endpt}, right: {r_endpt}")
    comparison_cnt = 0
    if l_endpt >= r_endpt:
        return
    pivot_idx = choose_pivot(arr, l_endpt, r_endpt - 1, method=pivot_method) # chose pivot index
    print(f"pivot index: {pivot_idx}, pivot={arr[pivot_idx]}")
    move_pivot_to_first(arr, l_endpt, pivot_idx) # move pivot to first element
    print(f"pivot moved to first: {arr}")
    new_pivot_idx = partition(arr, l_endpt, r_endpt) # parition array around pivot
    print(f"new pivot index: {new_pivot_idx}, new pivot={arr[new_pivot_idx]}")
    quick_sort(arr, l_endpt, new_pivot_idx - 1, pivot_method=pivot_method)
#     if len(arr[l_endpt:new_pivot_idx - 1]) - 1 > 0:
#         comparison_cnt += len(arr[l_endpt:new_pivot_idx - 1]) - 1
#         print(f"new comparison count: {comparison_cnt}")
    quick_sort(arr, new_pivot_idx + 1, r_endpt, pivot_method=pivot_method)
#     if len(arr[new_pivot_idx + 1:r_endpt]) - 1 > 0:
#         comparison_cnt += len(arr[new_pivot_idx + 1:r_endpt]) - 1
#         print(f"new comparison count: {comparison_cnt}")

In [300]:
# arr = np.array([3, 7, 1, 9, 1000, 456, 72])
arr = np.array([4, 1, 6, 2])
l = 0
r = len(arr)
method = 'median'
# print(f"original array: {arr}")
quick_sort(arr, l, r, pivot_method=method)
print(f"final sorted array: {arr}")

original array: [4 1 6 2]
pivot_method: median
left: 0, right: 4
nums in choose_pivot(): [4, 1, 2]
median in choose_pivot(): 2.0, will return 3
pivot index: 3, pivot=2
pivot moved to first: [2 1 6 4]
array to partition: [2 1 6 4]
pivot=2
j=1, i=1
1 is less than pivot (2) - do work
j=2, i=2
j=3, i=2
final array in partition: [1 2 6 4], returning new pivot index 1
new pivot index: 1, new pivot=2
original array: [1 2 6 4]
pivot_method: median
left: 0, right: 0
original array: [1 2 6 4]
pivot_method: median
left: 2, right: 4
nums in choose_pivot(): [6, 1, 4]
median in choose_pivot(): 4.0, will return 3
pivot index: 3, pivot=4
pivot moved to first: [1 2 4 6]
array to partition: [4 6]
pivot=4
j=3, i=3
final array in partition: [1 2 4 6], returning new pivot index 2
new pivot index: 2, new pivot=4
original array: [1 2 4 6]
pivot_method: median
left: 2, right: 1
original array: [1 2 4 6]
pivot_method: median
left: 3, right: 4
nums in choose_pivot(): [6, 6, 6]
median in choose_pivot(): 6.0, wil

In [277]:
fp = 'coursera_algo_nums_QuickSort.txt'
nums = load_text_file_to_array(fp)
fewer_nums = nums[:100]

In [278]:
l = 0
r = len(fewer_nums)
method = 'first'
print(f"original array: {fewer_nums}")
quick_sort(fewer_nums, l, r, pivot_method=method)
print(f"final sorted array: {fewer_nums}")

original array: [2148 9058 7742 3153 6324  609 7628 5469 7017  504 4092 1582 9572 1542
 5697 2081 4218 3130 7923 9595 6558 3859 9832 3062 6788 7578 7432  479
 8439 9079 7173 2667 2770 2655  972 4264 2014 3171 4715  345 4388 3816
 8887 3915 3490 2327  123 4596 4307 8737 4007 6798 6551 1627 1190 4984
 2480 3404 2027 4778 2951 2795 5002 8121 8910 9593 5254  448 6237 5565
 1816  392 8143 9310 9293 3138 4869 6756  872 6183 3517 3513 1676 5498
 9172 5739 6108 7538 7671 5780 8666  540 9771 6837 9341 1590 5689 1605
 1103 5859]
original array: [2148 9058 7742 3153 6324  609 7628 5469 7017  504 4092 1582 9572 1542
 5697 2081 4218 3130 7923 9595 6558 3859 9832 3062 6788 7578 7432  479
 8439 9079 7173 2667 2770 2655  972 4264 2014 3171 4715  345 4388 3816
 8887 3915 3490 2327  123 4596 4307 8737 4007 6798 6551 1627 1190 4984
 2480 3404 2027 4778 2951 2795 5002 8121 8910 9593 5254  448 6237 5565
 1816  392 8143 9310 9293 3138 4869 6756  872 6183 3517 3513 1676 5498
 9172 5739 6108 7538 7671 5780 86

In [169]:
l = 0
r = len(nums)
method = 'first'
print(f"original array: {nums[:10]}")
quick_sort(nums, l, r, pivot_method=method)
print(f"final sorted array: {nums[:10]}")

original array: [123 345 392 479 504 448 540 609 972 872]
pivot=123
j=1, i=1
j=2, i=1
j=3, i=1
j=4, i=1
j=5, i=1
j=6, i=1
j=7, i=1
j=8, i=1
j=9, i=1
j=10, i=1
j=11, i=1
j=12, i=1
j=13, i=1
j=14, i=1
j=15, i=1
j=16, i=1
j=17, i=1
j=18, i=1
j=19, i=1
j=20, i=1
j=21, i=1
j=22, i=1
j=23, i=1
j=24, i=1
j=25, i=1
j=26, i=1
j=27, i=1
j=28, i=1
j=29, i=1
j=30, i=1
j=31, i=1
j=32, i=1
j=33, i=1
j=34, i=1
j=35, i=1
j=36, i=1
j=37, i=1
j=38, i=1
j=39, i=1
j=40, i=1
j=41, i=1
j=42, i=1
j=43, i=1
j=44, i=1
j=45, i=1
j=46, i=1
j=47, i=1
j=48, i=1
j=49, i=1
j=50, i=1
j=51, i=1
j=52, i=1
j=53, i=1
j=54, i=1
j=55, i=1
j=56, i=1
j=57, i=1
j=58, i=1
j=59, i=1
j=60, i=1
j=61, i=1
j=62, i=1
j=63, i=1
j=64, i=1
j=65, i=1
j=66, i=1
j=67, i=1
j=68, i=1
j=69, i=1
j=70, i=1
j=71, i=1
j=72, i=1
j=73, i=1
j=74, i=1
j=75, i=1
j=76, i=1
j=77, i=1
j=78, i=1
j=79, i=1
j=80, i=1
j=81, i=1
j=82, i=1
j=83, i=1
j=84, i=1
j=85, i=1
j=86, i=1
j=87, i=1
j=88, i=1
j=89, i=1
j=90, i=1
j=91, i=1
j=92, i=1
j=93, i=1
j=94, i=1
j

KeyboardInterrupt: 

In [135]:
nums[:100]

array([  1,   3,   4,   2,   5,   9,  10,  11,  12,   6,  13,  14,  15,
         8,  16,  17,  18,  19,  20,  21,   7,  22,  23,  25,  24,  26,
        27,  28,  30,  29,  31,  32,  33,  34,  37,  38,  39,  35,  40,
        41,  42,  43,  44,  46,  45,  47,  48,  49,  50,  52,  53,  54,
        55,  57,  59,  58,  61,  56,  62,  63,  64,  65,  51,  66,  67,
        68,  69,  70,  72,  71,  73,  74,  76,  75,  77,  78,  80,  81,
        79,  82,  83,  85,  86,  84,  87,  88,  89,  90,  91,  92,  95,
        96,  94,  97,  98,  99, 100, 101, 102,  93])

In [187]:
theta = 0.4
n = 16

In [188]:
-1 * ((np.log(n)) / (np.log(1-theta)))

5.4276617954268955

In [189]:
-1 * ((np.log(n)) / (np.log(theta)))

3.0258831894641203

In [194]:
l = [3, 1, 6]
s = sorted(l)
int(np.median(s))

3

In [199]:
from math import floor
l = [3, 6, 1, 9, 2]
# l = [4, 5, 6, 7]
if len(l) % 2 == 0:
    mid_idx = len(l) // 2 - 1
else:
    mid_idx = len(l) // 2
mid_idx

2

In [217]:
arr = np.array([3, 1, 8])
med = 8
np.where(arr==med)[0][0]

2

In [96]:
l_endpt_idx = 2
r_endpt_idx = 5
arr = np.array([3, 2, 6, 8, 1, 9, 4])
method = 'last'
piv_idx = choose_pivot(arr, l_endpt_idx, r_endpt_idx, method=method)
print(f"pivot: {arr[piv_idx]}")

pivot: 9


In [105]:
arr = np.array([3, 2, 1, 8, 6, 9, 4])
l_endpt_idx = 1
r_endpt_idx = len(arr)
partition(arr, l_endpt_idx, r_endpt_idx)

pivot=2
j=2, i=2, array=[2 1 8 6 9 4]
1 is less than pivot - do work
j=3, i=3, array=[2 1 8 6 9 4]
j=4, i=3, array=[2 1 8 6 9 4]
j=5, i=3, array=[2 1 8 6 9 4]
j=6, i=3, array=[2 1 8 6 9 4]
final array: [3 1 2 8 6 9 4]


2

In [108]:
# arr = np.array([3, 2, 7, 1, 5])
# l_endpt = 0
# r_endpt = 5
# piv_idx = 3
# print(f"original array: {arr}")
# arr = move_pivot_to_first(arr, l_endpt, r_endpt, piv_idx)
# print(f"new array: {arr}")

In [83]:
arr = [3, 2, 8, 5, 1, 4, 7, 6]
# arr = np.array([6, 2, 9])
l = 0
r = len(arr)
print(f"original array: {arr}")
quick_sort(arr, l, r)
print(f"final sorted array: {arr}")

original array: [3, 2, 8, 5, 1, 4, 7, 6]
new comparison count: 6
new comparison count: 2
new comparison count: 4
final sorted array: [1, 2, 3, 4, 5, 6, 7, 8]


In [180]:
arr1 = [3, 2, 8, 5, 1, 4, 7, 6]
l = 0
r = 7
partition(arr1, l, r)

j=1, array=[3, 2, 8, 5, 1, 4, 7, 6]
2 is less than pivot - do work
new array: [3, 2, 8, 5, 1, 4, 7, 6]
j=2, array=[3, 2, 8, 5, 1, 4, 7, 6]
j=3, array=[3, 2, 8, 5, 1, 4, 7, 6]
j=4, array=[3, 2, 8, 5, 1, 4, 7, 6]
1 is less than pivot - do work
new array: [3, 2, 1, 5, 8, 4, 7, 6]
j=5, array=[3, 2, 1, 5, 8, 4, 7, 6]
j=6, array=[3, 2, 1, 5, 8, 4, 7, 6]


[1, 2, 3, 5, 8, 4, 7, 6]

In [167]:
arr = np.array([3, 8, 2, 5, 1, 4, 7, 6])
pivot = 3
for i in range(len(arr)):
    pivot_idx = np.where(arr == pivot)[0][0]
    if arr[i] < pivot:
        arr[pivot_idx - 1] = arr[i]
        arr[i] = pivot
        print(f"found smaller # than pivot, new array = {arr}")
    else:
        arr[pivot_idx + 1] = arr[i]
        arr[i] = pivot
        print(f"found smaller # than pivot, new array = {arr}")        

0

In [15]:
def fast_power(a, b):
    recursion_cnt = 0
    if b == 1:
        print('b == 1')
        return a
    else:
        c = a * a
        print(f"c = {c}")
        print(f"recursion count = {recursion_cnt}")
        recursion_cnt += 1
        ans = fast_power(c, b/2)
        print(f"answer = {ans}")
    if b % 2 != 0:
        print(f"b is odd, returning {a * ans}")
        return a * ans
    else:
        print(f"b is even, returning {ans}")
        return ans

In [16]:
a = 2
b = 4
answer = fast_power(a, b)
print(f"final answer: {answer}")

c = 4
recursion count = 0
c = 16
recursion count = 0
b == 1
answer = 16
b is even, returning 16
answer = 16
b is even, returning 16
final answer: 16


In [131]:
nums = []
file = open("coursera_algo_nums.txt", "r")
for line in file:
    nums.append(int(line.strip()))
nums[:10]

[54044, 14108, 79294, 29649, 25260, 60660, 2995, 53777, 49689, 9083]

In [132]:
nums = np.array(nums)

In [133]:
nums.shape

(100000,)

In [134]:
len(nums)

100000

In [152]:
def merge_and_count_split_inversions(arr1, arr2):
#     assert len(arr1) == len(arr2), "two arrays must be of equal length"
    merged_arr = np.zeros(len(arr1) + len(arr2))
    split_inv_cnt = 0
    i, j = 0, 0
    for k in range(len(merged_arr)):
#         print(f'current merged array: {merged_arr} (k={k}, i={i}, j={j})')
        if i > len(arr1)-1:
            merged_arr[k] = arr2[j]
            j += 1
        elif j > len(arr2)-1:
            merged_arr[k] = arr1[i]
            i += 1            
        elif arr1[i] < arr2[j]:
            merged_arr[k] = arr1[i]
            i += 1
        else:
            merged_arr[k] = arr2[j]
            j += 1
#             print(f'split inversion found! (incrementing count by {len(arr1[i:])})')
            split_inv_cnt += len(arr1[i:])
    return merged_arr, split_inv_cnt

In [153]:
# tests for merge_and_count_split_inversions()
# arr1 = [1, 3, 5]
# arr2 = [2, 4, 6]
# merged_arr, split_inv_cnt = merge_and_count_split_inversions(arr1, arr2)
# print(f"merged array: {merged_arr}\ntotal split inversions: {split_inv_cnt}")

# arr1 = np.array([1, 2, 3])
# arr2 = np.array([4, 5, 6])
# merged_arr, split_inv_cnt = merge_and_count_split_inversions(arr1, arr2)
# print(f"merged array: {merged_arr}\ntotal split inversions: {split_inv_cnt}")

# arr1 = np.array([1, 4, 6, 8])
# arr2 = np.array([2, 3, 5, 9])
# merged_arr, split_inv_cnt = merge_and_count_split_inversions(arr1, arr2)
# print(f"merged array: {merged_arr}\ntotal split inversions: {split_inv_cnt}")

In [156]:
def sort_and_count_inversions(num_array):
    if len(num_array) == 1:
        return (num_array, 0)
    else:
        mid_idx = len(num_array) // 2
        left = num_array[:mid_idx]
        right = num_array[mid_idx:]
#         print(f"left: {left}\nright: {right}")
        left_sorted, left_inv_cnt = sort_and_count_inversions(left)
        right_sorted, right_inv_cnt = sort_and_count_inversions(right)
        merged, split_inv_cnt = merge_and_count_split_inversions(left_sorted, right_sorted)
        total_inv_cnt = left_inv_cnt + right_inv_cnt + split_inv_cnt
#         print(f'merged: {merged}\ntotal inversions: {total_inv_cnt}')
        return (merged, total_inv_cnt)

In [158]:
# arr = np.array([1, 3, 5, 2, 4, 6])
arr = np.array([1, 6, 4, 8, 2, 3, 5, 9])
merged, inv_cnt = sort_and_count_inversions(arr)
print(f'original array: {arr}\nsorted array: {merged}\ntotal inversions: {inv_cnt}')

original array: [1 6 4 8 2 3 5 9]
sorted array: [1. 2. 3. 4. 5. 6. 8. 9.]
total inversions: 9


In [159]:
merged, inv_cnt = sort_and_count_inversions(nums)
print(f"total inversions in nums: {inv_cnt}")

total inversions in nums: 2407905288


In [160]:
merged[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [161]:
len(merged)

100000

In [162]:
merged

array([1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 9.9998e+04, 9.9999e+04,
       1.0000e+05])

In [47]:
def find_total_inversions(num_array):
    inv_cnt = 0
    for i in range(num_array.shape[0]):
        for j in range(1, num_array.shape[0]):
            if (num_array[i] > num_array[j]) & (i < j):
#                 print(f"{num_array[i]} > {num_array[j]}")
                inv_cnt += 1
#                 print(f"inversion count: {inv_cnt}")
    return inv_cnt

In [55]:
# find_total_inversions(nums)

KeyboardInterrupt: 

In [48]:
n = 6
# arr = np.array([6, 5, 4, 3, 2, 1])
arr = np.random.randint(1, 100, n)
print(f"array: {arr}\n")
find_total_inversions(arr)

array: [38 58 33 53 56 43]



7

In [45]:
arr = np.array([3, 2, 6, 1])
inv_cnt = 0
for i in range(arr.shape[0]):
    for j in range(1, arr.shape[0]):
        if (arr[i] > arr[j]) & (i < j):
            print(f"{arr[i]} > {arr[j]}")
            inv_cnt += 1
            print(f"inversion count: {inv_cnt}")
print(inv_cnt)


3 > 2
inversion count: 1
3 > 1
inversion count: 2
2 > 1
inversion count: 3
6 > 1
inversion count: 4
4


In [20]:
mid_idx = len(arr) // 2
right = arr[:mid_idx]
print(f"right: {right}")
left = arr[mid_idx:]
print(f"left: {left}")

right: [3 2]
left: [6 1 5]


In [7]:
list(range(0, arr.shape[0] - 1))

[0, 1, 2]

In [14]:
arr[len(arr) // 2]

6

In [38]:
def find_total_inversions(num_list):
    inv_cnt = 0
    if len(num_list) == 1:
        return 0
    if len(num_list) == 2:
#         print(f'length 2 list: {num_list}')
        if num_list[0] > num_list[1]:
#             print(f"returning 1 for {num_list}")
            return 1
        else:
            return 0
    else:
        mid_idx = len(num_list) // 2
        left = num_list[:mid_idx]
        right = num_list[mid_idx:]
#         print(f"left:{left}\nright: {right}")
        inv_cnt += find_total_inversions(right)
        inv_cnt += find_total_inversions(left)
#         print(f"new inv count: {inv_cnt}")
        return inv_cnt

In [40]:
n = 10
arr = np.array([6, 5, 4, 3, 2, 1])
# arr = np.random.randint(1, 100, n)
print(f"array: {arr}\n")
find_total_inversions(arr)

array: [6 5 4 3 2 1]



2

In [2]:
def multiply_integers(num1, num2):
    import time
    start = time.time()
    num1_list = [int(digit) for digit in str(num1)][::-1]
    num2_list = [int(digit) for digit in str(num2)][::-1]
    products = []
    for i in range(len(num1_list)):
        for j in range(len(num2_list)):
            product = num1_list[i] * num2_list[j] * (10**i) * (10**j)
            products.append(product)
    final = np.sum(products)
    end = time.time()
    elapsed = end - start
    print(f'multiplication took {elapsed} seconds')
    return final

In [3]:
n1 = 3141592653589793238462643383279502884197169399375105820974944592
n2 = 2718281828459045235360287471352662497757247093699959574966967627
# n1 = 12
# n2 = 45
print(f'actual product: {n1 * n2}')
print(f'calculated product: {multiply_integers(n1, n2)}')

actual product: 8539734222673567065463550869546574495034888535765114961879601127067743044893204848617875072216249073013374895871952806582723184
multiplication took 0.015227317810058594 seconds
calculated product: 8539734222673567065463550869546574495034888535765114961879601127067743044893204848617875072216249073013374895871952806582723184


In [4]:
def binary_search(sorted_array, num_to_find, low_idx, high_idx):
    pass

In [130]:
def merge_sort(array_to_sort):
    pass

def merged_two_sorted_arrays(arr1, arr2):
    assert len(arr1) == len(arr2), "two arrays must be of equal length"
    merged_arr = np.zeros(len(arr1) + len(arr2))
    i, j = 0, 0
    for k in range(len(merged_arr)):
        if i > len(arr1)-1:
            merged_arr[k] = arr2[j]
            j += 1
        elif j > len(arr2)-1:
            merged_arr[k] = arr1[i]
            i += 1            
        elif arr1[i] < arr2[j]:
            merged_arr[k] = arr1[i]
            i += 1
        else:
            merged_arr[k] = arr2[j]
            j += 1
    return merged_arr

In [ ]:
merge_sort()

In [86]:
# def merge_and_count_split_inversions(arr1, arr2): # old version
#     assert len(arr1) == len(arr2), "two arrays must be of equal length"
#     merged_arr = np.zeros(len(arr1) + len(arr2))
#     split_inv_cnt = 0
#     i = 0
#     j = 0
#     for k in range(len(merged_arr)):
#         print(f'current merged array: {merged_arr} (k={k}, i={i}, j={j})')
#         if i > len(arr1)-1:
#             merged_arr[k] = arr2[j]
#             j += 1
#             split_inv_cnt += 1
#         elif j > len(arr2)-1:
#             merged_arr[k] = arr1[i]
#             i += 1            
#         elif arr1[i] < arr2[j]:
#             merged_arr[k] = arr1[i]
#             i += 1
#         else:
#             split_inv_cnt += 1
#             merged_arr[k] = arr2[j]
#             j += 1
#     return merged_arr, split_inv_cnt

In [115]:
def merge_and_count_split_inversions(arr1, arr2):
    assert len(arr1) == len(arr2), "two arrays must be of equal length"
    merged_arr = np.zeros(len(arr1) + len(arr2))
    split_inv_cnt = 0
    i = 0
    j = 0
    for k in range(len(merged_arr)):
#         print(f'current merged array: {merged_arr} (k={k}, i={i}, j={j})')
        if i > len(arr1)-1:
            merged_arr[k] = arr2[j]
            j += 1
#             print('split inversion found!')
            split_inv_cnt += 1
        elif j > len(arr2)-1:
            merged_arr[k] = arr1[i]
            i += 1            
        elif arr1[i] < arr2[j]:
            merged_arr[k] = arr1[i]
            i += 1
        else:
            merged_arr[k] = arr2[j]
            j += 1
#             print('split inversion found!')
            split_inv_cnt += 1
    return merged_arr, split_inv_cnt